# Generated by Django 4.1.6 on 2023-03-01 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_mymodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyModel',
            new_name='DynamicModel',
        ),
    ]
