# Generated by Django 4.1.6 on 2023-03-15 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_rename_mymodel_dynamicmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DynamicModel',
        ),
    ]
